//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_LibraryEntities : DbContext
    {
        public db_LibraryEntities()
            : base("name=db_LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAutor> tblAutors { get; set; }
        public virtual DbSet<tblDenimet> tblDenimets { get; set; }
        public virtual DbSet<tblKasa> tblKasas { get; set; }
        public virtual DbSet<tblKategori> tblKategoris { get; set; }
        public virtual DbSet<tblLevizjet> tblLevizjets { get; set; }
        public virtual DbSet<tblLiber> tblLibers { get; set; }
        public virtual DbSet<tblPerdoruesit> tblPerdoruesits { get; set; }
        public virtual DbSet<tblPersoneli> tblPersonelis { get; set; }
        public virtual DbSet<tblRrethNesh> tblRrethNeshes { get; set; }
        public virtual DbSet<tblKontaktet> tblKontaktets { get; set; }
    }
}
