//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDenimet
    {
        public int ID { get; set; }
        public Nullable<int> Perdoruesi { get; set; }
        public Nullable<int> Levizja { get; set; }
        public Nullable<System.DateTime> DataFillimit { get; set; }
        public Nullable<System.DateTime> DataMbarimit { get; set; }
        public Nullable<decimal> DenimiLeke { get; set; }
    
        public virtual tblLevizjet tblLevizjet { get; set; }
        public virtual tblPerdoruesit tblPerdoruesit { get; set; }
    }
}
