//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKontaktet
    {
        public int ID { get; set; }
        public string Emri { get; set; }
        public string Mail { get; set; }
        public string tema { get; set; }
        public string Mesazhi { get; set; }
    }
}
