//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLevizjet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLevizjet()
        {
            this.tblDenimets = new HashSet<tblDenimet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Librat { get; set; }
        public Nullable<int> Perdoruesi { get; set; }
        public Nullable<int> Personeli { get; set; }
        public Nullable<System.DateTime> DataMarrjes { get; set; }
        public Nullable<System.DateTime> DataRikthimit { get; set; }
        public Nullable<bool> StatusiPuneve { get; set; }
        public Nullable<System.DateTime> DataRikthimitPerdoruesit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDenimet> tblDenimets { get; set; }
        public virtual tblLiber tblLiber { get; set; }
        public virtual tblPerdoruesit tblPerdoruesit { get; set; }
        public virtual tblPersoneli tblPersoneli { get; set; }
    }
}
