//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLiber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLiber()
        {
            this.tblLevizjets = new HashSet<tblLevizjet>();
        }
    
        public int ID { get; set; }
        public string Emri { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> AutorID { get; set; }
        public string VitiShtypjes { get; set; }
        public string ShtepiaBotuse { get; set; }
        public string Faqe { get; set; }
        public Nullable<bool> GjendjaLibrit { get; set; }
        public string FotoLibrit { get; set; }
    
        public virtual tblAutor tblAutor { get; set; }
        public virtual tblKategori tblKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLevizjet> tblLevizjets { get; set; }
    }
}
